# Generated by Django 5.2 on 2025-06-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_telegramdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramdata',
            name='auth_date',
        ),
        migrations.AddField(
            model_name='telegramdata',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='telegramdata',
            name='last_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
