# Generated by Django 5.2 on 2025-06-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_telegramuser_delete_telegramdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='auth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
