# Generated by Django 5.2 on 2025-05-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250502_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistic',
            options={'ordering': ['order'], 'verbose_name': 'Статистика', 'verbose_name_plural': 'Данные статистики'},
        ),
    ]
