# Generated by Django 5.2 on 2025-05-07 04:49

from django_ckeditor_5.fields import CKEditor5Field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_statistic_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_html',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=CKEditor5Field(help_text='Основной текст страницы', verbose_name='Содержание страницы'),
        ),
    ]
