# Generated by Django 5.2 on 2025-05-07 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_page_is_html_alter_page_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['title'], 'verbose_name': 'страницу', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterModelOptions(
            name='statistic',
            options={'ordering': ['order'], 'verbose_name': 'статистику', 'verbose_name_plural': 'Данные статистики'},
        ),
    ]
