# Generated by Django 5.2 on 2025-05-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_page_options_alter_statistic_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_html',
            field=models.BooleanField(default=False, help_text='Отметьте, если страница загружена из HTML-файла', verbose_name='HTML страница'),
        ),
    ]
