# Generated by Django 5.2 on 2025-06-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_page_is_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show_in_menu',
            field=models.BooleanField(default=False, verbose_name='Отображать в меню'),
        ),
    ]
