# Generated by Django 5.2 on 2025-06-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_page_show_in_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='show_in_menu',
            field=models.BooleanField(default=True, verbose_name='Отображать в меню'),
        ),
    ]
