# Generated by Django 5.2 on 2025-06-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_page_show_in_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_html',
            field=models.BooleanField(default=False, help_text='Отметьте, если страница синхронизируется с файлом шаблона', verbose_name='HTML страница'),
        ),
    ]
