# Generated by Django 5.2 on 2025-06-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_page_menu_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='menu_icon',
            field=models.CharField(choices=[('bi-file-earmark-text', 'Документ'), ('bi-file-code', 'Код'), ('bi-file-text', 'Текст'), ('bi-file-richtext', 'Форматированный текст'), ('bi-file-break', 'Разрыв'), ('bi-file-plus', 'Плюс'), ('bi-file-minus', 'Минус'), ('bi-file-check', 'Галочка'), ('bi-file-x', 'Крестик'), ('bi-file-image', 'Изображение'), ('bi-file-music', 'Музыка'), ('bi-file-play', 'Видео'), ('bi-file-zip', 'Архив'), ('bi-file-pdf', 'PDF'), ('bi-file-word', 'Word'), ('bi-file-excel', 'Excel'), ('bi-file-ppt', 'PowerPoint'), ('bi-house-door', 'Дом'), ('bi-chart-line', 'Ступенчатый график'), ('bi-graph-up', 'График'), ('bi-globe', 'Глобус'), ('bi-lightbulb', 'Лампочка'), ('bi-briefcase', 'Портфель')], default='bi-file-earmark-text', help_text='Выберите иконку для отображения в меню', max_length=50, verbose_name='Иконка меню'),
        ),
    ]
