# Generated by Django 5.2.1 on 2025-06-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_page_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['menu_order', 'title'], 'verbose_name': 'страницу', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.RemoveField(
            model_name='page',
            name='order',
        ),
        migrations.AddField(
            model_name='page',
            name='menu_order',
            field=models.PositiveIntegerField(default=0, help_text='Число для сортировки (меньше - выше в меню)', verbose_name='Порядок в меню'),
        ),
    ]
