# Generated by Django 5.2 on 2025-04-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryByCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('average_salary', models.FloatField()),
                ('vacancy_share', models.FloatField()),
                ('is_for_profession', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-average_salary'],
            },
        ),
        migrations.CreateModel(
            name='SalaryByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('average_salary', models.FloatField()),
                ('vacancy_count', models.IntegerField()),
                ('profession_average_salary', models.FloatField(blank=True, null=True)),
                ('profession_vacancy_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('count', models.IntegerField()),
                ('is_for_profession', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-year', '-count'],
            },
        ),
    ]
