# Generated by Django 5.2 on 2025-05-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarybycity',
            options={'ordering': ['-average_salary'], 'verbose_name': 'Статистика по городам', 'verbose_name_plural': 'Статистика по городам'},
        ),
        migrations.AlterModelOptions(
            name='salarybyyear',
            options={'ordering': ['year'], 'verbose_name': 'Статистика по годам', 'verbose_name_plural': 'Статистика по годам'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-year', '-count'], 'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AlterField(
            model_name='salarybycity',
            name='average_salary',
            field=models.FloatField(help_text='Средняя зарплата в рублях', verbose_name='Средняя зарплата'),
        ),
        migrations.AlterField(
            model_name='salarybycity',
            name='city',
            field=models.CharField(help_text='Название города', max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='salarybycity',
            name='is_for_profession',
            field=models.BooleanField(default=False, help_text='Отметка для статистики по конкретной профессии', verbose_name='Только для C# разработчиков'),
        ),
        migrations.AlterField(
            model_name='salarybycity',
            name='vacancy_share',
            field=models.FloatField(help_text='Доля вакансий в процентах', verbose_name='Доля вакансий'),
        ),
        migrations.AlterField(
            model_name='salarybyyear',
            name='average_salary',
            field=models.FloatField(help_text='Средняя зарплата в рублях', verbose_name='Средняя зарплата'),
        ),
        migrations.AlterField(
            model_name='salarybyyear',
            name='profession_average_salary',
            field=models.FloatField(blank=True, help_text='Средняя зарплата для C# разработчиков', null=True, verbose_name='Зарплата C# разработчика'),
        ),
        migrations.AlterField(
            model_name='salarybyyear',
            name='profession_vacancy_count',
            field=models.IntegerField(blank=True, help_text='Количество вакансий для C# разработчиков', null=True, verbose_name='Вакансии C# разработчика'),
        ),
        migrations.AlterField(
            model_name='salarybyyear',
            name='vacancy_count',
            field=models.IntegerField(help_text='Общее число вакансий', verbose_name='Количество вакансий'),
        ),
        migrations.AlterField(
            model_name='salarybyyear',
            name='year',
            field=models.IntegerField(help_text='Год сбора статистики', verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='count',
            field=models.IntegerField(help_text='Частота упоминания навыка', verbose_name='Количество упоминаний'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='is_for_profession',
            field=models.BooleanField(default=False, help_text='Отметка для навыков конкретной профессии', verbose_name='Только для C# разработчиков'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(help_text='Название навыка', max_length=100, verbose_name='Навык'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='year',
            field=models.IntegerField(help_text='Год сбора данных', verbose_name='Год'),
        ),
    ]
