# Generated by Django 5.2 on 2025-05-07 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_salarybycity_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarybycity',
            options={'ordering': ['-average_salary'], 'verbose_name': 'статистику по городам', 'verbose_name_plural': 'Статистика по городам'},
        ),
        migrations.AlterModelOptions(
            name='salarybyyear',
            options={'ordering': ['year'], 'verbose_name': 'статистику по годам', 'verbose_name_plural': 'Статистика по годам'},
        ),
    ]
