# Generated by Django 5.2.1 on 2025-05-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_salarybycity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarybycity',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarybycity',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='salarybycity',
            table='salary_by_city',
        ),
    ]
