# Generated by Django 5.2.1 on 2025-05-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_salarybycity_lat_salarybycity_lon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarybycity',
            name='lat',
            field=models.FloatField(blank=True, help_text='Координата X от экватора', null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='salarybycity',
            name='lon',
            field=models.FloatField(blank=True, help_text='Координата Y от экватора', null=True, verbose_name='Долгота'),
        ),
    ]
