# Generated by Django 5.2 on 2025-05-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_skill_analytics_s_count_08d6fc_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_count_threshold', models.IntegerField(default=50, help_text='Навыки с частотой ниже этого значения не будут отображаться', verbose_name='Порог частоты навыков')),
            ],
            options={
                'verbose_name': 'настройку аналитики',
                'verbose_name_plural': 'Настройки аналитики',
            },
        ),
    ]
