# Generated by Django 5.2 on 2025-06-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_analyticssettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название настройки')),
                ('desktop_height', models.PositiveIntegerField(default=500, verbose_name='Высота на десктопе (px)')),
                ('mobile_height', models.PositiveIntegerField(default=300, verbose_name='Высота на мобильных (px)')),
                ('maintain_aspect_ratio', models.BooleanField(default=False, verbose_name='Сохранять пропорции')),
            ],
            options={
                'verbose_name': 'Настройка графиков',
                'verbose_name_plural': 'Настройки графиков',
            },
        ),
    ]
