# Generated by Django 5.2 on 2025-06-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_chartsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartsettings',
            name='desktop_height',
            field=models.PositiveIntegerField(default=500, verbose_name='Высота на пк версии (px)'),
        ),
    ]
