# Generated by Django 5.2 on 2025-06-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_alter_chartsettings_desktop_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartsettings',
            name='chart_type',
            field=models.CharField(choices=[('demand', 'Графики востребованности'), ('geography', 'Графики географии'), ('skills', 'Графики навыков')], default='demand', max_length=20, verbose_name='Тип графика'),
        ),
    ]
