# Generated by Django 5.2 on 2025-06-05 14:35

import analytics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_chartsettings_chart_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartsettings',
            name='desktop_width',
            field=models.PositiveIntegerField(default=100, help_text='Используйте число от 1 до 100 для процентов или больше для пикселей', validators=[analytics.models.validate_width], verbose_name='Ширина на пк версии (px или %)'),
        ),
        migrations.AddField(
            model_name='chartsettings',
            name='mobile_width',
            field=models.PositiveIntegerField(default=100, help_text='Используйте число от 1 до 100 для процентов или больше для пикселей', validators=[analytics.models.validate_width], verbose_name='Ширина на мобильных (px или %)'),
        ),
        migrations.AlterField(
            model_name='chartsettings',
            name='desktop_height',
            field=models.PositiveIntegerField(default=500, validators=[analytics.models.validate_height], verbose_name='Высота на пк версии (px)'),
        ),
        migrations.AlterField(
            model_name='chartsettings',
            name='mobile_height',
            field=models.PositiveIntegerField(default=300, validators=[analytics.models.validate_height], verbose_name='Высота на мобильных (px)'),
        ),
    ]
