# Generated by Django 5.2 on 2025-04-28 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_statistic_options_alter_page_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['title'], 'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterModelOptions(
            name='statistic',
            options={'ordering': ['order'], 'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистические данные'},
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(help_text='Основной текст страницы', verbose_name='Содержание страницы'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение для страницы', null=True, upload_to='pages/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, help_text='Уникальный идентификатор страницы для URL', unique=True, verbose_name='URL-адрес'),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='chart_image',
            field=models.ImageField(help_text='Изображение с графиком', upload_to='charts/', verbose_name='График'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Число для сортировки (меньше - выше)', verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='page',
            field=models.ForeignKey(help_text='Страница, к которой привязана статистика', on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='core.page', verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='table_html',
            field=models.TextField(help_text='HTML-код таблицы с данными', verbose_name='HTML таблицы'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='title',
            field=models.CharField(help_text='Заголовок для блока статистики', max_length=200, verbose_name='Название статистики'),
        ),
    ]
