# Generated by Django 5.2 on 2025-05-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-published_at'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='company_logo',
            field=models.URLField(blank=True, null=True, verbose_name='Лого компании'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.CharField(help_text='Название компании-работодателя', max_length=200, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(help_text='Подробное описание вакансии', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateTimeField(help_text='Когда вакансия была опубликована', verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='region',
            field=models.CharField(help_text='Географическое расположение', max_length=100, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(help_text='Уровень зарплаты', max_length=100, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='skills',
            field=models.TextField(help_text='Список необходимых навыков', verbose_name='Требуемые навыки'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(help_text='Заголовок вакансии', max_length=200, verbose_name='Название вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='url',
            field=models.URLField(help_text='URL оригинальной вакансии', verbose_name='Ссылка на вакансию'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['-published_at'], name='vacancies_v_publish_38d5cd_idx'),
        ),
    ]
