# Generated by Django 5.2 on 2025-05-07 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_vacancy_options_vacancy_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-published_at'], 'verbose_name': 'вакансию', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
