# Generated by Django 5.2.1 on 2025-05-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_alter_vacancy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='salary_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
